using System.Globalization;

namespace ChromeNativeAdblock.Gui;

internal static class LocalizationService
{
    public const string Vietnamese = "vi";
    public const string English = "en";
    public const string Chinese = "zh";

    public static event Action? LanguageChanged;

    private static readonly string SettingsPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "ChromeNativeAdblock",
        "language.txt");

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Translations =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            [Vietnamese] = new Dictionary<string, string>
            {
                ["AppTitle"] = "Chrome Native Adblock",
                ["AppSubtitle"] = "Chrome Adblock & MV2 Launcher",
                ["HeroTitle"] = "Chrome Native Adblock",
                ["HeroSubtitle"] = "Chặn quảng cáo tốc độ cao bằng RAM Hook & Mở khóa tiện ích Manifest V2 (uBlock Origin, Tampermonkey) trực tiếp trong RAM không làm mất bảo mật.",
                ["LanguageLabel"] = "Ngôn ngữ / Language",
                ["ChromeStatusHeader"] = "Trạng thái Google Chrome",
                ["ChromeReady"] = "Google Chrome đã sẵn sàng",
                ["ChromeRunning"] = "Chrome đang hoạt động (Active)",
                ["RunningBadge"] = "Active",
                ["ChromeNotFound"] = "Không tìm thấy cài đặt Google Chrome",
                ["ChromeAnalyzing"] = "Đang phân tích chrome.exe và chrome.dll...",
                ["ChromeVersionLabel"] = "Phiên bản:",
                ["ChromePathLabel"] = "Đường dẫn:",
                ["Feature1Title"] = "Chặn quảng cáo Native (RAM Hook)",
                ["Feature1Desc"] = "Hook Network Service trong RAM, chặn sạch quảng cáo mạng & bypass quảng cáo YouTube tức thì không tốn CPU.",
                ["Feature2Title"] = "Bật lại Manifest V2 trong RAM",
                ["Feature2Desc"] = "Vá RAM chrome.dll tự động mở khóa uBlock Origin MV2, Tampermonkey MV2 và tự động sửa lỗi Preferences profile.",
                ["Feature3Title"] = "Tự động cập nhật bộ lọc (EasyList, ABPVN, YouTube)",
                ["Feature3Desc"] = "Tự động đồng bộ hóa các bộ lọc EasyList, EasyPrivacy, ABPVN và YouTube rules mới nhất.",
                ["OpenExtensionsCheckBox"] = "Mở trang tiện ích (chrome://extensions) khi khởi chạy",
                ["LaunchButton"] = "Patch & Khởi chạy Chrome",
                ["LaunchingText"] = "Đang khởi chạy Chrome...",
                ["RunningStatus"] = "Chrome đang hoạt động (PID: {0})",
                ["StopButton"] = "Dừng Chrome",
                ["MinimizeToTrayButton"] = "Ẩn xuống khay hệ thống",
                ["RefreshButton"] = "Làm mới",
                ["LiveConsoleHeader"] = "Nhật ký Hoạt động Trực tiếp (Live Activity Console)",
                ["ClearLogsButton"] = "Xóa log",
                ["CopyLogsButton"] = "Sao chép",
                ["BlockedCounterBadge"] = "Đã chặn: {0} requests",
                ["YouTubeAdsBadge"] = "YouTube bypass: {0}",
                ["TechnicalDetailsHeader"] = "Thông tin kỹ thuật & Phân tích PE",
                ["CopySuccess"] = "Đã sao chép nhật ký vào Clipboard!",
                ["TrayOpen"] = "Mở ứng dụng (Open)",
                ["TrayLaunch"] = "Khởi chạy Chrome (Launch)",
                ["TrayStop"] = "Dừng Chrome (Stop)",
                ["TrayExit"] = "Thoát (Exit)",
                ["TrayNotificationTitle"] = "Chrome Native Adblock",
                ["TrayNotificationBody"] = "Ứng dụng đang chạy ngầm trong khay hệ thống. Nhấp đúp để mở lại.",
                ["TrayTooltip"] = "Chrome Native Adblock",

                // Filter Management Panel & Sticky Action Bar
                ["FilterPanelHeader"] = "Quản lý Bộ lọc (Filter Lists)",
                ["FilterPanelSubtitle"] = "Tùy chỉnh danh sách bộ lọc theo chuẩn uBlock Origin. Bật/tắt linh hoạt và tự động hợp nhất vào bộ nhớ RAM.",
                ["ApplyChangesButton"] = "Áp dụng các thay đổi",
                ["UpdateFiltersButton"] = "Cập nhật ngay",
                ["RestoreDefaultsButton"] = "Khôi phục mặc định",
                ["UpdatingFiltersText"] = "Đang tải & cập nhật bộ lọc...",
                ["ApplyingChangesText"] = "Đang áp dụng thay đổi bộ lọc...",
                ["FilterCountSummaryFormat"] = "Đã dùng {0} trên {1}",
                ["FilterUsedBadgeFormat"] = "Đã dùng {0} trên {1}",
                ["TotalFiltersActiveFormat"] = "Đã bật: {0}/{1} danh sách ({2:N0} quy tắc)",
                ["RulesCountFormat"] = "{0:N0} quy tắc",
                ["RulesWord"] = "quy tắc",
                ["FilterNotDownloaded"] = "Chưa tải",
                ["FilterApplySuccess"] = "Đã áp dụng các thay đổi thành công! ({0:N0} quy tắc)",
                ["FilterUpdatedSuccess"] = "Đã cập nhật tất cả bộ lọc thành công! ({0:N0} quy tắc, {1} danh sách)",
                ["FilterRestoreSuccess"] = "Đã khôi phục các bộ lọc về mặc định.",
                ["FilterToggleLog"] = "Đã {0} bộ lọc '{1}' (Tổng số quy tắc: {2:N0})",
                ["FilterActionEnabled"] = "bật",
                ["FilterActionDisabled"] = "tắt",

                // Presets
                ["PresetSelectorHeader"] = "Chế độ chặn cấu hình sẵn (Blocking Presets)",
                ["Preset_Basic"] = "Cơ bản",
                ["Preset_Basic_Sub"] = "~140K quy tắc",
                ["Preset_Basic_Desc"] = "Tối ưu tốc độ cao (~140.000 quy tắc). Chặn quảng cáo cơ bản, phù hợp máy cấu hình nhẹ.",
                ["Preset_Standard"] = "Tiêu chuẩn (Khuyên dùng)",
                ["Preset_Standard_Sub"] = "~220K quy tắc",
                ["Preset_Standard_Desc"] = "Cân bằng hoàn hảo giữa hiệu năng và khả năng chặn (~220.000 quy tắc). Khuyên dùng cho mọi nhu cầu.",
                ["Preset_Advanced"] = "Nâng cao",
                ["Preset_Advanced_Sub"] = "~450K quy tắc",
                ["Preset_Advanced_Desc"] = "Chặn sạch quảng cáo, mã độc, Cookie & Pop-up phiền toái (~450.000 quy tắc).",
                ["Preset_Max"] = "Tối đa",
                ["Preset_Max_Sub"] = "~650K+ quy tắc",
                ["Preset_Max_Desc"] = "Bảo vệ tối đa toàn diện, chống theo dõi chuyên sâu (~650.000+ quy tắc).",
                ["Preset_Custom"] = "Tùy chỉnh",
                ["Preset_Custom_Sub"] = "Theo lựa chọn",
                ["Preset_Custom_Desc"] = "Cấu hình tùy biến theo danh sách bộ lọc bạn tự chọn.",
                ["PresetSwitchedLog"] = "Đã chuyển sang chế độ chặn: '{0}' ({1} danh sách)",

                // 9 Categories
                ["Category_Builtin"] = "Dựng sẵn / Built-in",
                ["Category_Builtin_Desc"] = "Quy tắc cốt lõi uBlock Origin chống rủi ro mã độc và sửa lỗi web.",
                ["Category_Core"] = "Dựng sẵn / Built-in",
                ["Category_Core_Desc"] = "Quy tắc cốt lõi uBlock Origin chống rủi ro mã độc và sửa lỗi web.",
                ["Category_Ads"] = "Quảng cáo / Ads",
                ["Category_Ads_Desc"] = "Chặn quảng cáo mạng, pop-up, video ads và banner tài trợ.",
                ["Category_Privacy"] = "Riêng tư / Privacy",
                ["Category_Privacy_Desc"] = "Bảo vệ quyền riêng tư, chặn theo dõi hành vi và telemetry.",
                ["Category_Security"] = "Chặn mã độc, bảo mật / Malware & Security",
                ["Category_Security_Desc"] = "Chặn tên miền độc hại, lừa đảo phishing và ransomware.",
                ["Category_Multipurpose"] = "Đa chức năng / Multipurpose",
                ["Category_Multipurpose_Desc"] = "Các danh sách máy chủ quảng cáo và file hosts tổng hợp.",
                ["Category_Cookies"] = "Các thông báo cookie / Cookie Notices",
                ["Category_Cookies_Desc"] = "Tự động ẩn và loại bỏ các hộp thoại xin phép cookie GDPR.",
                ["Category_Social"] = "Tiện ích xã hội / Social Widgets",
                ["Category_Social_Desc"] = "Chặn các nút chia sẻ mạng xã hội, like button và widget theo dõi.",
                ["Category_Annoyances"] = "Phiền toái / Annoyances",
                ["Category_Annoyances_Desc"] = "Loại bỏ cửa sổ đăng ký nhận tin, khảo sát pop-up và thông báo đẩy.",
                ["Category_Regions"] = "Khu vực, ngôn ngữ / Regions & Languages",
                ["Category_Regions_Desc"] = "Bộ lọc tối ưu hóa cho các trang web theo từng khu vực và ngôn ngữ.",

                // Sub-Groups
                ["SubGroup_uBlockFilters"] = "uBlock filters",
                ["SubGroup_uBlockFilters_Desc"] = "Quy tắc cốt lõi uBlock Origin",
                ["SubGroup_EasyListCookies"] = "EasyList/uBO – Cookie Notices",
                ["SubGroup_EasyListCookies_Desc"] = "Thông báo cookie từ EasyList và uBlock Origin",
                ["SubGroup_AdGuardCookies"] = "AdGuard/uBO – Cookie Notices",
                ["SubGroup_AdGuardCookies_Desc"] = "Thông báo cookie từ AdGuard và uBlock Origin",
                ["SubGroup_EasyListAnnoyances"] = "EasyList – Annoyances",
                ["SubGroup_EasyListAnnoyances_Desc"] = "Bộ lọc phiền toái từ EasyList (AI, Chat, Newsletters, Notifications)",
                ["SubGroup_AdGuardAnnoyances"] = "AdGuard – Annoyances",
                ["SubGroup_AdGuardAnnoyances_Desc"] = "Bộ lọc phiền toái từ AdGuard (Banners, Popups, Widgets)",
                ["SubGroup_Pl"] = "pl: Oficjalne Polskie Filtry",
                ["SubGroup_Pl_Desc"] = "Bộ lọc chính thức cho các trang web tiếng Ba Lan",
                ["SubGroup_Ru"] = "ru, ua, uz, kz: RU AdList",
                ["SubGroup_Ru_Desc"] = "Bộ lọc RU AdList dành cho các trang web tiếng Nga và khu vực SNG",

                // Filter Items (72 Items)
                // 1. Builtin
                ["Filter_ublock_filters_Name"] = "uBlock filters – Ads",
                ["Filter_ublock_filters_Desc"] = "Bộ lọc cơ bản của uBlock Origin loại bỏ quảng cáo và chống phá hoại.",
                ["Filter_ublock_badware_Name"] = "uBlock filters – Badware risks",
                ["Filter_ublock_badware_Desc"] = "Chặn các tên miền nguy hiểm và mã độc rủi ro cao từ uBlock Origin.",
                ["Filter_ublock_privacy_Name"] = "uBlock filters – Privacy",
                ["Filter_ublock_privacy_Desc"] = "Bảo vệ quyền riêng tư và chặn theo dõi hành vi nâng cao.",
                ["Filter_ublock_quick_fixes_Name"] = "uBlock filters – Quick fixes",
                ["Filter_ublock_quick_fixes_Desc"] = "Bản vá sửa lỗi nhanh cho các trang web và trình phát video phổ biến.",
                ["Filter_ublock_unbreak_Name"] = "uBlock filters – Unbreak",
                ["Filter_ublock_unbreak_Desc"] = "Khắc phục lỗi hiển thị và chống vỡ giao diện trên các trang web.",
                ["Filter_ublock_experimental_Name"] = "uBlock filters – Experimental",
                ["Filter_ublock_experimental_Desc"] = "Các bộ lọc thử nghiệm mới nhất của uBlock Origin.",

                // 2. Ads
                ["Filter_easylist_Name"] = "EasyList",
                ["Filter_easylist_Desc"] = "Danh sách chặn quảng cáo phổ biến và toàn diện nhất thế giới.",
                ["Filter_adguard_base_Name"] = "AdGuard – Ads",
                ["Filter_adguard_base_Desc"] = "Bộ lọc quảng cáo toàn diện tiêu chuẩn từ AdGuard Team.",
                ["Filter_adguard_mobile_Name"] = "AdGuard – Mobile Ads",
                ["Filter_adguard_mobile_Desc"] = "Bộ lọc quảng cáo tối ưu cho giao diện di động và ứng dụng web.",
                ["Filter_youtube_adblock_Name"] = "YouTube Adblock & Scriptlets",
                ["Filter_youtube_adblock_Desc"] = "Chặn quảng cáo, biểu ngữ tài trợ và video ads trên YouTube.",

                // 3. Privacy
                ["Filter_easyprivacy_Name"] = "EasyPrivacy",
                ["Filter_easyprivacy_Desc"] = "Ngăn chặn toàn diện các trình theo dõi hành vi, phân tích và telemetry.",
                ["Filter_adguard_tracking_Name"] = "AdGuard/uBO – URL Tracking Protection",
                ["Filter_adguard_tracking_Desc"] = "Xóa các tham số theo dõi hành vi (utm, fbclid, gclid) trên URL.",
                ["Filter_block_lan_Name"] = "Block Outsider Intrusion into LAN",
                ["Filter_block_lan_Desc"] = "Ngăn chặn các trang web bên ngoài xâm nhập và quét mạng nội bộ LAN.",

                // 4. Security
                ["Filter_malicious_urls_Name"] = "Online Malicious URL Blocklist",
                ["Filter_malicious_urls_Desc"] = "Chặn các liên kết chứa mã độc, virus và trang web độc hại từ URLhaus.",
                ["Filter_phishing_urls_Name"] = "Phishing URL Blocklist",
                ["Filter_phishing_urls_Desc"] = "Chặn các trang web lừa đảo trực tuyến (phishing) và giả mạo ngân hàng.",

                // 5. Multipurpose
                ["Filter_peter_lowe_Name"] = "Peter Lowe’s Ad and tracking server list",
                ["Filter_peter_lowe_Desc"] = "Danh sách máy chủ quảng cáo và theo dõi của Peter Lowe.",
                ["Filter_dan_pollock_Name"] = "Dan Pollock’s hosts file",
                ["Filter_dan_pollock_Desc"] = "File hosts chặn quảng cáo và tên miền rác nổi tiếng của Dan Pollock.",

                // 6. Cookies
                ["Filter_easylist_cookies_Name"] = "EasyList – Cookie Notices",
                ["Filter_easylist_cookies_Desc"] = "Tự động ẩn và chặn các hộp thoại xin phép cookie (EasyList / Fanboy).",
                ["Filter_ublock_cookies_easylist_Name"] = "uBlock filters – Cookie Notices",
                ["Filter_ublock_cookies_easylist_Desc"] = "Bộ lọc thông báo cookie bổ sung của uBlock Origin.",
                ["Filter_adguard_cookies_Name"] = "AdGuard – Cookie Notices",
                ["Filter_adguard_cookies_Desc"] = "Bộ lọc thông báo cookie từ AdGuard Team.",
                ["Filter_ublock_cookies_adguard_Name"] = "uBlock filters – Cookie Notices",
                ["Filter_ublock_cookies_adguard_Desc"] = "Bộ lọc thông báo cookie bổ sung kết hợp cùng AdGuard.",

                // 7. Social
                ["Filter_easylist_social_Name"] = "EasyList – Social Widgets",
                ["Filter_easylist_social_Desc"] = "Chặn các nút chia sẻ Facebook, Twitter, mạng xã hội (Fanboy Social).",
                ["Filter_adguard_social_Name"] = "AdGuard – Social Widgets",
                ["Filter_adguard_social_Desc"] = "Bộ lọc tiện ích mạng xã hội tiêu chuẩn từ AdGuard.",
                ["Filter_fanboy_antifacebook_Name"] = "Fanboy – Anti-Facebook",
                ["Filter_fanboy_antifacebook_Desc"] = "Chặn hoàn toàn các tiện ích, theo dõi và nội dung nhúng Facebook.",

                // 8. Annoyances
                ["Filter_easylist_ai_Name"] = "EasyList – AI Widgets",
                ["Filter_easylist_ai_Desc"] = "Chặn các tiện ích chatbot AI và hộp thoại AI hỗ trợ nổi trên web.",
                ["Filter_easylist_chat_Name"] = "EasyList – Chat Widgets",
                ["Filter_easylist_chat_Desc"] = "Chặn các hộp thoại hỗ trợ khách hàng và live chat tự bật.",
                ["Filter_easylist_newsletters_Name"] = "EasyList – Newsletter Notices",
                ["Filter_easylist_newsletters_Desc"] = "Ẩn các pop-up xin đăng ký nhận email bản tin (newsletter).",
                ["Filter_easylist_notifications_Name"] = "EasyList – Notifications",
                ["Filter_easylist_notifications_Desc"] = "Chặn các thông báo đẩy và nhắc nhở trên trình duyệt.",
                ["Filter_easylist_other_annoyances_Name"] = "EasyList – Other Annoyances",
                ["Filter_easylist_other_annoyances_Desc"] = "Loại bỏ các phần tử gây phiền toái khác từ EasyList.",
                ["Filter_adguard_mobile_app_banners_Name"] = "AdGuard – Mobile App Banners",
                ["Filter_adguard_mobile_app_banners_Desc"] = "Ẩn các biểu ngữ mời cài đặt ứng dụng di động.",
                ["Filter_adguard_other_annoyances_Name"] = "AdGuard – Other Annoyances",
                ["Filter_adguard_other_annoyances_Desc"] = "Bộ lọc các yếu tố gây phiền toái khác từ AdGuard.",
                ["Filter_adguard_popup_overlays_Name"] = "AdGuard – Popup Overlays",
                ["Filter_adguard_popup_overlays_Desc"] = "Chặn các lớp phủ pop-up chặn đọc nội dung trang.",
                ["Filter_adguard_widgets_Name"] = "AdGuard – Widgets",
                ["Filter_adguard_widgets_Desc"] = "Ẩn các tiện ích nổi và widget gây mất tập trung từ AdGuard.",
                ["Filter_ublock_annoyances_Name"] = "uBlock filters – Annoyances",
                ["Filter_ublock_annoyances_Desc"] = "Bộ lọc loại bỏ phiền toái tổng hợp của uBlock Origin.",

                // 9. Regions (38 items)
                ["Filter_reg_al_Name"] = "al, xk: Adblock List for Albania",
                ["Filter_reg_al_Desc"] = "Bộ lọc quảng cáo cho các trang web Albania và Kosovo.",
                ["Filter_reg_bg_Name"] = "bg: Bulgarian Adblock list",
                ["Filter_reg_bg_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Bulgaria.",
                ["Filter_reg_cn_Name"] = "cn, tw: AdGuard Chinese (中文)",
                ["Filter_reg_cn_Desc"] = "Chặn quảng cáo trên các trang web tiếng Trung Quốc.",
                ["Filter_reg_cz_Name"] = "cz, sk: EasyList Czech and Slovak",
                ["Filter_reg_cz_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Séc và Slovakia.",
                ["Filter_reg_de_Name"] = "de, ch, at: EasyList Germany",
                ["Filter_reg_de_Desc"] = "Bộ lọc quảng cáo bổ sung cho các trang web tiếng Đức.",
                ["Filter_reg_ee_Name"] = "ee: Eesti saitidele kohandatud filter",
                ["Filter_reg_ee_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Estonia.",
                ["Filter_reg_eg_Name"] = "eg, sa, ma, dz: Liste AR",
                ["Filter_reg_eg_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Ả Rập.",
                ["Filter_reg_es_pt_Name"] = "es, ar, br, pt: AdGuard Spanish/Portuguese",
                ["Filter_reg_es_pt_Desc"] = "Bộ lọc quảng cáo cho tiếng Tây Ban Nha và Bồ Đào Nha.",
                ["Filter_reg_es_Name"] = "es, ar, mx, co: EasyList Spanish",
                ["Filter_reg_es_Desc"] = "Bộ lọc quảng cáo EasyList tiếng Tây Ban Nha.",
                ["Filter_reg_fi_Name"] = "fi: Adblock List for Finland",
                ["Filter_reg_fi_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Phần Lan.",
                ["Filter_reg_fr_Name"] = "fr, be, ca: AdGuard Français",
                ["Filter_reg_fr_Desc"] = "Bộ lọc quảng cáo dành riêng cho các trang web tiếng Pháp.",
                ["Filter_reg_gr_Name"] = "gr, cy: Greek AdBlock Filter",
                ["Filter_reg_gr_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Hy Lạp.",
                ["Filter_reg_hr_Name"] = "hr, rs: Dandelion Sprout's Serbo-Croatian filters",
                ["Filter_reg_hr_Desc"] = "Bộ lọc cho các trang web Serbia, Croatia và Bosnia.",
                ["Filter_reg_hu_Name"] = "hu: hufilter",
                ["Filter_reg_hu_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Hungary.",
                ["Filter_reg_id_Name"] = "id, my: ABPindo",
                ["Filter_reg_id_Desc"] = "Bộ lọc quảng cáo cho các trang web Indonesia và Malaysia.",
                ["Filter_reg_il_Name"] = "il: EasyList Hebrew",
                ["Filter_reg_il_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Do Thái (Hebrew).",
                ["Filter_reg_in_Name"] = "in, lk, np: IndianList",
                ["Filter_reg_in_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Ấn Độ, Sri Lanka, Nepal.",
                ["Filter_reg_ir_Name"] = "ir: PersianBlocker",
                ["Filter_reg_ir_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Ba Tư (Iran).",
                ["Filter_reg_is_Name"] = "is: Icelandic ABP List",
                ["Filter_reg_is_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Iceland.",
                ["Filter_reg_it_Name"] = "it: EasyList Italy",
                ["Filter_reg_it_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Ý.",
                ["Filter_reg_jp_Name"] = "jp: AdGuard Japanese",
                ["Filter_reg_jp_Desc"] = "Chặn quảng cáo trên các trang web tiếng Nhật.",
                ["Filter_reg_kr_Name"] = "kr: 한국어 (Korean)",
                ["Filter_reg_kr_Desc"] = "Bộ lọc quảng cáo tối ưu cho các trang web tiếng Hàn Quốc.",
                ["Filter_reg_lt_Name"] = "lt: EasyList Lithuania",
                ["Filter_reg_lt_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Litva.",
                ["Filter_reg_lv_Name"] = "lv: Latvian List",
                ["Filter_reg_lv_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Latvia.",
                ["Filter_reg_mk_Name"] = "mk: Macedonian adBlock Filters",
                ["Filter_reg_mk_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Macedonia.",
                ["Filter_reg_nl_Name"] = "nl, be: AdGuard Dutch",
                ["Filter_reg_nl_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Hà Lan và Bỉ.",
                ["Filter_reg_no_Name"] = "no, dk, is: Dandelion Sprouts nordiske filtre",
                ["Filter_reg_no_Desc"] = "Bộ lọc cho các nước Bắc Âu (Na Uy, Đan Mạch, Iceland).",
                ["Filter_reg_pl_cert_Name"] = "pl: CERT.PL's Warning List",
                ["Filter_reg_pl_cert_Desc"] = "Danh sách cảnh báo tên miền độc hại của CERT Ba Lan.",
                ["Filter_reg_pl_polskie_Name"] = "pl: Oficjalne Polskie Filtry do uBlocka Origin",
                ["Filter_reg_pl_polskie_Desc"] = "Bộ lọc chính thức cho uBlock Origin tại Ba Lan.",
                ["Filter_reg_ro_Name"] = "ro, md: Romanian Ad (ROad) Block List Light",
                ["Filter_reg_ro_Desc"] = "Bộ lọc quảng cáo cho các trang web Romania và Moldova.",
                ["Filter_reg_ru_adlist_Name"] = "ru, ua, uz, kz: RU AdList",
                ["Filter_reg_ru_adlist_Desc"] = "Bộ lọc chính cho các trang web tiếng Nga và khu vực SNG.",
                ["Filter_reg_ru_counters_Name"] = "ru, ua, uz, kz: RU AdList: Counters",
                ["Filter_reg_ru_counters_Desc"] = "Chặn các bộ đếm và phân tích lưu lượng tại khu vực tiếng Nga.",
                ["Filter_reg_se_Name"] = "se: Frellwit's Swedish Filter",
                ["Filter_reg_se_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Thụy Điển.",
                ["Filter_reg_si_Name"] = "si: Slovenian List",
                ["Filter_reg_si_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Slovenia.",
                ["Filter_reg_th_Name"] = "th: EasyList Thailand",
                ["Filter_reg_th_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Thái Lan.",
                ["Filter_reg_tr_Name"] = "tr: AdGuard Turkish",
                ["Filter_reg_tr_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Thổ Nhĩ Kỳ.",
                ["Filter_reg_ua_Name"] = "ua: AdGuard Ukrainian",
                ["Filter_reg_ua_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Ukraina.",
                ["Filter_reg_vn_Name"] = "vn: ABPVN List",
                ["Filter_reg_vn_Desc"] = "Bộ lọc tối ưu hóa dành riêng cho các trang web và báo điện tử tại Việt Nam.",
                ["Filter_reg_pl_Name"] = "pl: Oficjalne Polskie Filtry",
                ["Filter_reg_pl_Desc"] = "Bộ lọc quảng cáo chính thức dành riêng cho các trang web và báo điện tử tại Ba Lan.",
                ["ProfileModeLabel"] = "Hồ sơ Chrome / Profile",
                ["ProfileMode_Managed"] = "Hồ sơ riêng (Khuyên dùng)",
                ["ProfileMode_ManagedNote"] = "Hồ sơ riêng tại %LOCALAPPDATA%\\ChromeNativeAdblock\\Profile. Đầy đủ tính năng, kể cả chặn cosmetic (CDP) và console trực tiếp.",
                ["ProfileMode_Real"] = "Hồ sơ Chrome gốc của tôi (giữ đăng nhập)",
                ["ProfileMode_RealNote"] = "Chrome 136+ chặn remote debugging trên hồ sơ gốc: chặn cosmetic và console trực tiếp sẽ không chạy, nhưng chặn quảng cáo mạng và MV2 vẫn hoạt động. Hồ sơ gốc sẽ được MV2 repair chỉnh sửa.",
                ["ProfileMode_RealMissingNote"] = "Không tìm thấy hồ sơ gốc: ",

                // Legacy aliases
                ["Filter_fanboy_cookiemonster_Name"] = "EasyList – Cookie Notices",
                ["Filter_fanboy_cookiemonster_Desc"] = "Tự động ẩn và chặn các hộp thoại xin phép cookie (EasyList / Fanboy).",
                ["Filter_fanboy_annoyance_Name"] = "EasyList – Annoyances",
                ["Filter_fanboy_annoyance_Desc"] = "Chặn pop-up khảo sát, thông báo đẩy, tiện ích chat và thanh thông báo nổi.",
                ["Filter_adguard_annoyances_Name"] = "AdGuard – Annoyances",
                ["Filter_adguard_annoyances_Desc"] = "Loại bỏ thông báo tự bật, cửa sổ đăng ký nhận tin và thông báo cookie từ AdGuard.",
                ["Filter_abpvn_Name"] = "vn: ABPVN List",
                ["Filter_abpvn_Desc"] = "Bộ lọc tối ưu hóa dành riêng cho các trang web và báo điện tử tại Việt Nam.",
                ["Filter_adguard_chinese_Name"] = "cn, tw: AdGuard Chinese (中文)",
                ["Filter_adguard_chinese_Desc"] = "Chặn quảng cáo trên các trang web tiếng Trung Quốc.",
                ["Filter_easylist_germany_Name"] = "de, ch, at: EasyList Germany",
                ["Filter_easylist_germany_Desc"] = "Bộ lọc quảng cáo bổ sung cho các trang web tiếng Đức.",
                ["Filter_adguard_japanese_Name"] = "jp: AdGuard Japanese",
                ["Filter_adguard_japanese_Desc"] = "Chặn quảng cáo và phần tử rác trên các trang web tiếng Nhật.",
                ["Filter_korean_list_Name"] = "kr: 한국어 (Korean)",
                ["Filter_korean_list_Desc"] = "Bộ lọc quảng cáo tối ưu cho các trang web tiếng Hàn Quốc.",
                ["Filter_adguard_french_Name"] = "fr, be, ca: AdGuard Français",
                ["Filter_adguard_french_Desc"] = "Bộ lọc quảng cáo dành riêng cho các trang web tiếng Pháp.",
                ["Filter_adguard_spanish_Name"] = "es, ar, br, pt: AdGuard Spanish/Portuguese",
                ["Filter_adguard_spanish_Desc"] = "Bộ lọc quảng cáo dành cho các trang web tiếng Tây Ban Nha.",
                ["Filter_adguard_russian_Name"] = "ru, ua, uz, kz: RU AdList",
                ["Filter_adguard_russian_Desc"] = "Bộ lọc quảng cáo cho các trang web tiếng Nga."
            },
            [English] = new Dictionary<string, string>
            {
                ["AppTitle"] = "Chrome Native Adblock",
                ["AppSubtitle"] = "Chrome Adblock & MV2 Launcher",
                ["HeroTitle"] = "Chrome Native Adblock",
                ["HeroSubtitle"] = "High-performance Native RAM Hook adblocking & Manifest V2 extension enabler (uBlock Origin, Tampermonkey) directly in RAM without disabling security.",
                ["LanguageLabel"] = "Language",
                ["ChromeStatusHeader"] = "Google Chrome Status",
                ["ChromeReady"] = "Google Chrome is ready",
                ["ChromeRunning"] = "Chrome is running (Active)",
                ["RunningBadge"] = "Active",
                ["ChromeNotFound"] = "Google Chrome installation was not found",
                ["ChromeAnalyzing"] = "Analyzing chrome.exe and chrome.dll...",
                ["ChromeVersionLabel"] = "Version:",
                ["ChromePathLabel"] = "Path:",
                ["Feature1Title"] = "Native Adblock (RAM Hook)",
                ["Feature1Desc"] = "Directly hooks Network Service in RAM, blocks network ads & zero-overhead YouTube bypass.",
                ["Feature2Title"] = "Manifest V2 Enabler",
                ["Feature2Desc"] = "Patches chrome.dll in RAM to re-enable uBlock Origin MV2, Tampermonkey MV2 and auto-repair profile preferences.",
                ["Feature3Title"] = "Auto-update Filters (EasyList, ABPVN, YouTube)",
                ["Feature3Desc"] = "Automatically downloads and synchronizes latest EasyList, EasyPrivacy, ABPVN, and YouTube filter rules.",
                ["OpenExtensionsCheckBox"] = "Open extensions page (chrome://extensions) on launch",
                ["LaunchButton"] = "Patch & Launch Chrome",
                ["LaunchingText"] = "Launching Chrome...",
                ["RunningStatus"] = "Chrome is running (PID: {0})",
                ["StopButton"] = "Stop Chrome",
                ["MinimizeToTrayButton"] = "Minimize to Tray",
                ["RefreshButton"] = "Refresh",
                ["LiveConsoleHeader"] = "Real-time Live Activity Console",
                ["ClearLogsButton"] = "Clear Logs",
                ["CopyLogsButton"] = "Copy",
                ["BlockedCounterBadge"] = "Blocked: {0} requests",
                ["YouTubeAdsBadge"] = "YouTube bypass: {0}",
                ["TechnicalDetailsHeader"] = "Technical Details & PE Analysis",
                ["CopySuccess"] = "Logs copied to Clipboard!",
                ["TrayOpen"] = "Open Application",
                ["TrayLaunch"] = "Launch Chrome",
                ["TrayStop"] = "Stop Chrome",
                ["TrayExit"] = "Exit",
                ["TrayNotificationTitle"] = "Chrome Native Adblock",
                ["TrayNotificationBody"] = "Application is running in the system tray. Double-click to restore.",
                ["TrayTooltip"] = "Chrome Native Adblock",

                // Filter Management Panel & Sticky Action Bar
                ["FilterPanelHeader"] = "Filter Lists Management",
                ["FilterPanelSubtitle"] = "Customize uBlock Origin compatible filter subscriptions. Toggle on/off and automatically merge in RAM.",
                ["ApplyChangesButton"] = "Apply Changes",
                ["UpdateFiltersButton"] = "Update Now",
                ["RestoreDefaultsButton"] = "Restore Defaults",
                ["UpdatingFiltersText"] = "Downloading & updating filters...",
                ["ApplyingChangesText"] = "Applying filter changes...",
                ["FilterCountSummaryFormat"] = "Used {0} of {1}",
                ["FilterUsedBadgeFormat"] = "Used {0} of {1}",
                ["TotalFiltersActiveFormat"] = "Active: {0}/{1} lists ({2:N0} rules)",
                ["RulesCountFormat"] = "{0:N0} rules",
                ["RulesWord"] = "rules",
                ["FilterNotDownloaded"] = "Not downloaded",
                ["FilterApplySuccess"] = "Filter changes applied successfully! ({0:N0} rules)",
                ["FilterUpdatedSuccess"] = "All filter lists updated successfully! ({0:N0} rules, {1} lists)",
                ["FilterRestoreSuccess"] = "Filter lists have been restored to defaults.",
                ["FilterToggleLog"] = "{0} filter '{1}' (Total rules: {2:N0})",
                ["FilterActionEnabled"] = "Enabled",
                ["FilterActionDisabled"] = "Disabled",

                // Presets
                ["PresetSelectorHeader"] = "Blocking Presets",
                ["Preset_Basic"] = "Basic",
                ["Preset_Basic_Sub"] = "~140K rules",
                ["Preset_Basic_Desc"] = "Ultra-fast speed (~140,000 rules). Basic ad blocking, best for lightweight systems.",
                ["Preset_Standard"] = "Standard (Recommended)",
                ["Preset_Standard_Sub"] = "~220K rules",
                ["Preset_Standard_Desc"] = "Perfect balance of performance and ad blocking (~220,000 rules). Recommended for everyone.",
                ["Preset_Advanced"] = "Advanced",
                ["Preset_Advanced_Sub"] = "~450K rules",
                ["Preset_Advanced_Desc"] = "Block ads, malware, cookie notices & annoying popups (~450,000 rules).",
                ["Preset_Max"] = "Max Protection",
                ["Preset_Max_Sub"] = "~650K+ rules",
                ["Preset_Max_Desc"] = "Ultimate protection against all ads, tracking & annoyances (~650,000+ rules).",
                ["Preset_Custom"] = "Custom",
                ["Preset_Custom_Sub"] = "User selection",
                ["Preset_Custom_Desc"] = "Custom selection based on your chosen filter lists.",
                ["PresetSwitchedLog"] = "Switched to blocking preset: '{0}' ({1} lists)",

                // 9 Categories
                ["Category_Builtin"] = "Built-in / Core (uBlock Filters)",
                ["Category_Builtin_Desc"] = "Core filter rules from uBlock Origin for badware protection, unbreak, and security.",
                ["Category_Core"] = "Built-in / Core (uBlock Filters)",
                ["Category_Core_Desc"] = "Core filter rules from uBlock Origin for badware protection, unbreak, and security.",
                ["Category_Ads"] = "Ads",
                ["Category_Ads_Desc"] = "Blocks banner ads, popups, video ads, and sponsored network content.",
                ["Category_Privacy"] = "Privacy",
                ["Category_Privacy_Desc"] = "Protects privacy by blocking behavioral trackers, analytics, and telemetry.",
                ["Category_Security"] = "Malware & Security",
                ["Category_Security_Desc"] = "Blocks phishing domains, malware distributors, and malicious web resources.",
                ["Category_Multipurpose"] = "Multipurpose",
                ["Category_Multipurpose_Desc"] = "Comprehensive ad and tracking server lists and hosts files.",
                ["Category_Cookies"] = "Cookie Notices",
                ["Category_Cookies_Desc"] = "Automatically hides and dismisses GDPR cookie consent notices.",
                ["Category_Social"] = "Social Widgets",
                ["Category_Social_Desc"] = "Blocks social media buttons, like widgets, and tracking plugins.",
                ["Category_Annoyances"] = "Annoyances",
                ["Category_Annoyances_Desc"] = "Eliminates newsletter overlays, survey popups, and push notifications.",
                ["Category_Regions"] = "Regions & Languages",
                ["Category_Regions_Desc"] = "Filter lists tailored for specific countries, regions, and native languages.",

                // Sub-Groups
                ["SubGroup_uBlockFilters"] = "uBlock filters",
                ["SubGroup_uBlockFilters_Desc"] = "Core rules from uBlock Origin",
                ["SubGroup_EasyListCookies"] = "EasyList/uBO – Cookie Notices",
                ["SubGroup_EasyListCookies_Desc"] = "Cookie notices from EasyList and uBlock Origin",
                ["SubGroup_AdGuardCookies"] = "AdGuard/uBO – Cookie Notices",
                ["SubGroup_AdGuardCookies_Desc"] = "Cookie notices from AdGuard and uBlock Origin",
                ["SubGroup_EasyListAnnoyances"] = "EasyList – Annoyances",
                ["SubGroup_EasyListAnnoyances_Desc"] = "EasyList annoyances filter list (AI, Chat, Newsletters, Notifications)",
                ["SubGroup_AdGuardAnnoyances"] = "AdGuard – Annoyances",
                ["SubGroup_AdGuardAnnoyances_Desc"] = "AdGuard annoyances filter list (Banners, Popups, Widgets)",
                ["SubGroup_Pl"] = "pl: Oficjalne Polskie Filtry",
                ["SubGroup_Pl_Desc"] = "Official Polish filter list for uBlock Origin",
                ["SubGroup_Ru"] = "ru, ua, uz, kz: RU AdList",
                ["SubGroup_Ru_Desc"] = "RU AdList filter for Russian and CIS regional sites",

                // Filter Items (72 Items)
                ["Filter_ublock_filters_Name"] = "uBlock filters – Ads",
                ["Filter_ublock_filters_Desc"] = "uBlock Origin foundational filter list for ad removal and anti-circumvention.",
                ["Filter_ublock_badware_Name"] = "uBlock filters – Badware risks",
                ["Filter_ublock_badware_Desc"] = "Blocks malicious domains and high-risk badware resources.",
                ["Filter_ublock_privacy_Name"] = "uBlock filters – Privacy",
                ["Filter_ublock_privacy_Desc"] = "Advanced privacy protection and behavioral tracker blocking.",
                ["Filter_ublock_quick_fixes_Name"] = "uBlock filters – Quick fixes",
                ["Filter_ublock_quick_fixes_Desc"] = "Rapid-response fixes for broken websites and video players.",
                ["Filter_ublock_unbreak_Name"] = "uBlock filters – Unbreak",
                ["Filter_ublock_unbreak_Desc"] = "Fixes display anomalies and prevents site breakage.",
                ["Filter_ublock_experimental_Name"] = "uBlock filters – Experimental",
                ["Filter_ublock_experimental_Desc"] = "Latest experimental filters from uBlock Origin.",

                ["Filter_easylist_Name"] = "EasyList",
                ["Filter_easylist_Desc"] = "The primary and most comprehensive global ad-blocking subscription.",
                ["Filter_adguard_base_Name"] = "AdGuard – Ads",
                ["Filter_adguard_base_Desc"] = "Standard comprehensive ad-filtering list from AdGuard Team.",
                ["Filter_adguard_mobile_Name"] = "AdGuard – Mobile Ads",
                ["Filter_adguard_mobile_Desc"] = "Ad-blocking filter list optimized for mobile web and apps.",
                ["Filter_youtube_adblock_Name"] = "YouTube Adblock & Scriptlets",
                ["Filter_youtube_adblock_Desc"] = "Blocks video ads, sponsored overlays, and ad banners across YouTube.",

                ["Filter_easyprivacy_Name"] = "EasyPrivacy",
                ["Filter_easyprivacy_Desc"] = "Comprehensive tracker, analytics, and telemetry blocking list.",
                ["Filter_adguard_tracking_Name"] = "AdGuard/uBO – URL Tracking Protection",
                ["Filter_adguard_tracking_Desc"] = "Removes tracking query parameters (utm, fbclid, gclid) from URLs.",
                ["Filter_block_lan_Name"] = "Block Outsider Intrusion into LAN",
                ["Filter_block_lan_Desc"] = "Blocks external websites from probing and accessing local LAN resources.",

                ["Filter_malicious_urls_Name"] = "Online Malicious URL Blocklist",
                ["Filter_malicious_urls_Desc"] = "Blocks phishing domains, malware distributors, and scam websites.",
                ["Filter_phishing_urls_Name"] = "Phishing URL Blocklist",
                ["Filter_phishing_urls_Desc"] = "Blocks online phishing links and fraudulent banking sites.",

                ["Filter_peter_lowe_Name"] = "Peter Lowe’s Ad and tracking server list",
                ["Filter_peter_lowe_Desc"] = "Peter Lowe's list of adservers and tracking domains.",
                ["Filter_dan_pollock_Name"] = "Dan Pollock’s hosts file",
                ["Filter_dan_pollock_Desc"] = "Famous hosts file by Dan Pollock blocking ads and junk domains.",

                ["Filter_easylist_cookies_Name"] = "EasyList – Cookie Notices",
                ["Filter_easylist_cookies_Desc"] = "Automatically blocks annoying cookie consent banners (Fanboy).",
                ["Filter_ublock_cookies_easylist_Name"] = "uBlock filters – Cookie Notices",
                ["Filter_ublock_cookies_easylist_Desc"] = "Complementary cookie notices filter from uBlock Origin.",
                ["Filter_adguard_cookies_Name"] = "AdGuard – Cookie Notices",
                ["Filter_adguard_cookies_Desc"] = "Cookie notices filter list from AdGuard Team.",
                ["Filter_ublock_cookies_adguard_Name"] = "uBlock filters – Cookie Notices",
                ["Filter_ublock_cookies_adguard_Desc"] = "Complementary cookie notices filter paired with AdGuard.",

                ["Filter_easylist_social_Name"] = "EasyList – Social Widgets",
                ["Filter_easylist_social_Desc"] = "Blocks social media sharing buttons and tracking widgets (Fanboy).",
                ["Filter_adguard_social_Name"] = "AdGuard – Social Widgets",
                ["Filter_adguard_social_Desc"] = "Social widgets and plugins filter from AdGuard Team.",
                ["Filter_fanboy_antifacebook_Name"] = "Fanboy – Anti-Facebook",
                ["Filter_fanboy_antifacebook_Desc"] = "Completely blocks Facebook embeds, tracking widgets, and scripts.",

                ["Filter_easylist_ai_Name"] = "EasyList – AI Widgets",
                ["Filter_easylist_ai_Desc"] = "Blocks AI chatbot overlays and assistive floating widgets.",
                ["Filter_easylist_chat_Name"] = "EasyList – Chat Widgets",
                ["Filter_easylist_chat_Desc"] = "Blocks popup customer support live chats and messaging widgets.",
                ["Filter_easylist_newsletters_Name"] = "EasyList – Newsletter Notices",
                ["Filter_easylist_newsletters_Desc"] = "Hides newsletter signup popups and subscribe dialogs.",
                ["Filter_easylist_notifications_Name"] = "EasyList – Notifications",
                ["Filter_easylist_notifications_Desc"] = "Blocks browser push notification prompts and nags.",
                ["Filter_easylist_other_annoyances_Name"] = "EasyList – Other Annoyances",
                ["Filter_easylist_other_annoyances_Desc"] = "Removes general miscellaneous visual annoyances from EasyList.",
                ["Filter_adguard_mobile_app_banners_Name"] = "AdGuard – Mobile App Banners",
                ["Filter_adguard_mobile_app_banners_Desc"] = "Hides prompts prompting mobile app installation.",
                ["Filter_adguard_other_annoyances_Name"] = "AdGuard – Other Annoyances",
                ["Filter_adguard_other_annoyances_Desc"] = "Filter for miscellaneous website annoyances from AdGuard.",
                ["Filter_adguard_popup_overlays_Name"] = "AdGuard – Popup Overlays",
                ["Filter_adguard_popup_overlays_Desc"] = "Blocks paywalls, popup overlays, and blocking dialogs.",
                ["Filter_adguard_widgets_Name"] = "AdGuard – Widgets",
                ["Filter_adguard_widgets_Desc"] = "Hides floating distraction widgets and page overlay elements.",
                ["Filter_ublock_annoyances_Name"] = "uBlock filters – Annoyances",
                ["Filter_ublock_annoyances_Desc"] = "Comprehensive annoyance removal filter from uBlock Origin.",

                ["Filter_reg_al_Name"] = "al, xk: Adblock List for Albania",
                ["Filter_reg_al_Desc"] = "Ad-blocking filter for Albanian and Kosovar websites.",
                ["Filter_reg_bg_Name"] = "bg: Bulgarian Adblock list",
                ["Filter_reg_bg_Desc"] = "Ad-blocking filter for Bulgarian websites.",
                ["Filter_reg_cn_Name"] = "cn, tw: AdGuard Chinese (中文)",
                ["Filter_reg_cn_Desc"] = "Comprehensive adblock list for Chinese websites.",
                ["Filter_reg_cz_Name"] = "cz, sk: EasyList Czech and Slovak",
                ["Filter_reg_cz_Desc"] = "Ad-blocking filter for Czech and Slovak websites.",
                ["Filter_reg_de_Name"] = "de, ch, at: EasyList Germany",
                ["Filter_reg_de_Desc"] = "Additional ad-blocking filter for German-language websites.",
                ["Filter_reg_ee_Name"] = "ee: Eesti saitidele kohandatud filter",
                ["Filter_reg_ee_Desc"] = "Ad-blocking filter for Estonian websites.",
                ["Filter_reg_eg_Name"] = "eg, sa, ma, dz: Liste AR",
                ["Filter_reg_eg_Desc"] = "Ad-blocking filter for Arabic-language websites.",
                ["Filter_reg_es_pt_Name"] = "es, ar, br, pt: AdGuard Spanish/Portuguese",
                ["Filter_reg_es_pt_Desc"] = "Ad-filtering list for Spanish and Portuguese websites.",
                ["Filter_reg_es_Name"] = "es, ar, mx, co: EasyList Spanish",
                ["Filter_reg_es_Desc"] = "EasyList ad-blocking filter for Spanish-language websites.",
                ["Filter_reg_fi_Name"] = "fi: Adblock List for Finland",
                ["Filter_reg_fi_Desc"] = "Ad-blocking filter for Finnish websites.",
                ["Filter_reg_fr_Name"] = "fr, be, ca: AdGuard Français",
                ["Filter_reg_fr_Desc"] = "Ad-filtering list dedicated to French-language websites.",
                ["Filter_reg_gr_Name"] = "gr, cy: Greek AdBlock Filter",
                ["Filter_reg_gr_Desc"] = "Ad-blocking filter for Greek websites.",
                ["Filter_reg_hr_Name"] = "hr, rs: Dandelion Sprout's Serbo-Croatian filters",
                ["Filter_reg_hr_Desc"] = "Filter for Serbian, Croatian, and Bosnian websites.",
                ["Filter_reg_hu_Name"] = "hu: hufilter",
                ["Filter_reg_hu_Desc"] = "Ad-blocking filter for Hungarian websites.",
                ["Filter_reg_id_Name"] = "id, my: ABPindo",
                ["Filter_reg_id_Desc"] = "Ad-blocking filter for Indonesian and Malaysian websites.",
                ["Filter_reg_il_Name"] = "il: EasyList Hebrew",
                ["Filter_reg_il_Desc"] = "Ad-blocking filter for Hebrew websites.",
                ["Filter_reg_in_Name"] = "in, lk, np: IndianList",
                ["Filter_reg_in_Desc"] = "Ad-blocking filter for Indian, Sri Lankan, and Nepali websites.",
                ["Filter_reg_ir_Name"] = "ir: PersianBlocker",
                ["Filter_reg_ir_Desc"] = "Ad-blocking filter for Persian (Iranian) websites.",
                ["Filter_reg_is_Name"] = "is: Icelandic ABP List",
                ["Filter_reg_is_Desc"] = "Ad-blocking filter for Icelandic websites.",
                ["Filter_reg_it_Name"] = "it: EasyList Italy",
                ["Filter_reg_it_Desc"] = "Ad-blocking filter for Italian websites.",
                ["Filter_reg_jp_Name"] = "jp: AdGuard Japanese",
                ["Filter_reg_jp_Desc"] = "Blocks ads and clutter on Japanese language websites.",
                ["Filter_reg_kr_Name"] = "kr: 한국어 (Korean)",
                ["Filter_reg_kr_Desc"] = "Optimized ad-filtering subscription for Korean websites.",
                ["Filter_reg_lt_Name"] = "lt: EasyList Lithuania",
                ["Filter_reg_lt_Desc"] = "Ad-blocking filter for Lithuanian websites.",
                ["Filter_reg_lv_Name"] = "lv: Latvian List",
                ["Filter_reg_lv_Desc"] = "Ad-blocking filter for Latvian websites.",
                ["Filter_reg_mk_Name"] = "mk: Macedonian adBlock Filters",
                ["Filter_reg_mk_Desc"] = "Ad-blocking filter for Macedonian websites.",
                ["Filter_reg_nl_Name"] = "nl, be: AdGuard Dutch",
                ["Filter_reg_nl_Desc"] = "Ad-blocking filter for Dutch and Belgian websites.",
                ["Filter_reg_no_Name"] = "no, dk, is: Dandelion Sprouts nordiske filtre",
                ["Filter_reg_no_Desc"] = "Nordic filter for Norway, Denmark, and Iceland.",
                ["Filter_reg_pl_cert_Name"] = "pl: CERT.PL's Warning List",
                ["Filter_reg_pl_cert_Desc"] = "Malicious domain warning list by Polish CERT.",
                ["Filter_reg_pl_polskie_Name"] = "pl: Oficjalne Polskie Filtry do uBlocka Origin",
                ["Filter_reg_pl_polskie_Desc"] = "Official Polish filter list for uBlock Origin.",
                ["Filter_reg_ro_Name"] = "ro, md: Romanian Ad (ROad) Block List Light",
                ["Filter_reg_ro_Desc"] = "Ad-blocking filter for Romanian and Moldovan websites.",
                ["Filter_reg_ru_adlist_Name"] = "ru, ua, uz, kz: RU AdList",
                ["Filter_reg_ru_adlist_Desc"] = "Comprehensive adblock subscription for Russian websites.",
                ["Filter_reg_ru_counters_Name"] = "ru, ua, uz, kz: RU AdList: Counters",
                ["Filter_reg_ru_counters_Desc"] = "Blocks web counters and analytics in Russian region.",
                ["Filter_reg_se_Name"] = "se: Frellwit's Swedish Filter",
                ["Filter_reg_se_Desc"] = "Ad-blocking filter for Swedish websites.",
                ["Filter_reg_si_Name"] = "si: Slovenian List",
                ["Filter_reg_si_Desc"] = "Ad-blocking filter for Slovenian websites.",
                ["Filter_reg_th_Name"] = "th: EasyList Thailand",
                ["Filter_reg_th_Desc"] = "Ad-blocking filter for Thai websites.",
                ["Filter_reg_tr_Name"] = "tr: AdGuard Turkish",
                ["Filter_reg_tr_Desc"] = "Ad-blocking filter for Turkish websites.",
                ["Filter_reg_ua_Name"] = "ua: AdGuard Ukrainian",
                ["Filter_reg_ua_Desc"] = "Ad-blocking filter for Ukrainian websites.",
                ["Filter_reg_vn_Name"] = "vn: ABPVN List",
                ["Filter_reg_vn_Desc"] = "Specialized ad-filtering list optimized for Vietnamese websites.",
                ["Filter_reg_pl_Name"] = "pl: Oficjalne Polskie Filtry",
                ["Filter_reg_pl_Desc"] = "Official Polish ad-filtering list for Polish websites and news portals.",
                ["ProfileModeLabel"] = "Chrome profile",
                ["ProfileMode_Managed"] = "Dedicated profile (recommended)",
                ["ProfileMode_ManagedNote"] = "Uses the dedicated %LOCALAPPDATA%\\ChromeNativeAdblock\\Profile. Every feature is active, including cosmetic filtering (CDP) and the live console.",
                ["ProfileMode_Real"] = "My original Chrome profile (keeps logins)",
                ["ProfileMode_RealNote"] = "Chrome 136+ blocks remote debugging on the original profile: cosmetic filtering and the live console will not run; network ad blocking and MV2 stay active. The MV2 repair modifies this profile.",
                ["ProfileMode_RealMissingNote"] = "Original profile not found: ",
            },
            [Chinese] = new Dictionary<string, string>
            {
                ["AppTitle"] = "Chrome Native Adblock",
                ["AppSubtitle"] = "Chrome 原生广告拦截与 MV2 扩展启动器",
                ["HeroTitle"] = "Chrome Native Adblock",
                ["HeroSubtitle"] = "基于内存的原生 Chrome 广告拦截与 Manifest V2 扩展恢复工具，无需修改磁盘文件，完全保护浏览器安全。",
                ["LanguageLabel"] = "语言 / Language",
                ["ChromeStatusHeader"] = "Google Chrome 状态",
                ["ChromeReady"] = "Google Chrome 已就绪",
                ["ChromeRunning"] = "Chrome 正在运行 (Active)",
                ["RunningBadge"] = "Active",
                ["ChromeNotFound"] = "未检测到 Google Chrome",
                ["ChromeAnalyzing"] = "正在分析 chrome.exe 和 chrome.dll...",
                ["ChromeVersionLabel"] = "版本:",
                ["ChromePathLabel"] = "路径:",
                ["Feature1Title"] = "原生广告拦截 (RAM Hook)",
                ["Feature1Desc"] = "直接在内存的 Network Service 拦截网络请求，零开销跳过 YouTube 广告与去除网页空白。",
                ["Feature2Title"] = "启用 Manifest V2 扩展",
                ["Feature2Desc"] = "在内存中解锁 Chrome 限制，恢复 uBlock Origin MV2、Tampermonkey 等扩展，并自动修复配置文件。",
                ["Feature3Title"] = "自动更新规则 (EasyList, ABPVN, YouTube)",
                ["Feature3Desc"] = "自动下载并同步最新的 EasyList、EasyPrivacy、ABPVN 和 YouTube 过滤规则。",
                ["OpenExtensionsCheckBox"] = "启动时打开扩展管理页面 (chrome://extensions)",
                ["LaunchButton"] = "修补并启动 Chrome",
                ["LaunchingText"] = "正在启动 Chrome...",
                ["RunningStatus"] = "Chrome 正在运行 (PID: {0})",
                ["StopButton"] = "停止 Chrome",
                ["MinimizeToTrayButton"] = "最小化到系统托盘",
                ["RefreshButton"] = "刷新",
                ["LiveConsoleHeader"] = "实时活动日志",
                ["ClearLogsButton"] = "清空日志",
                ["CopyLogsButton"] = "复制",
                ["BlockedCounterBadge"] = "已拦截请求: {0}",
                ["YouTubeAdsBadge"] = "YouTube 广告跳过: {0}",
                ["TechnicalDetailsHeader"] = "技术细节与 PE 分析",
                ["CopySuccess"] = "日志已复制到剪贴板！",
                ["TrayOpen"] = "打开主界面 (Open)",
                ["TrayLaunch"] = "启动 Chrome (Launch)",
                ["TrayStop"] = "停止 Chrome (Stop)",
                ["TrayExit"] = "退出 (Exit)",
                ["TrayNotificationTitle"] = "Chrome Native Adblock",
                ["TrayNotificationBody"] = "应用程序已最小化到系统托盘。双击托盘图标重新打开。",
                ["TrayTooltip"] = "Chrome Native Adblock",

                // Filter Management Panel & Sticky Action Bar
                ["FilterPanelHeader"] = "过滤规则管理 (Filter Lists)",
                ["FilterPanelSubtitle"] = "自定义 uBlock Origin 标准过滤规则列表。支持自由启闭并自动合并至内存。",
                ["ApplyChangesButton"] = "应用更改",
                ["UpdateFiltersButton"] = "立即更新",
                ["RestoreDefaultsButton"] = "恢复默认",
                ["UpdatingFiltersText"] = "正在下载并更新过滤规则...",
                ["ApplyingChangesText"] = "正在应用规则更改...",
                ["FilterCountSummaryFormat"] = "已使用 {0} / {1}",
                ["FilterUsedBadgeFormat"] = "已使用 {0} / {1}",
                ["TotalFiltersActiveFormat"] = "已启用: {0}/{1} 列表 ({2:N0} 条规则)",
                ["RulesCountFormat"] = "{0:N0} 条规则",
                ["RulesWord"] = "条规则",
                ["FilterApplySuccess"] = "规则更改已成功应用！({0:N0} 条规则)",
                ["FilterUpdatedSuccess"] = "所有过滤规则更新成功！({0:N0} 条规则, {1} 个列表)",
                ["FilterRestoreSuccess"] = "过滤规则已恢复为默认设置。",
                ["FilterToggleLog"] = "已{0}规则 '{1}' (总规则数: {2:N0})",
                ["FilterActionEnabled"] = "启用",
                ["FilterActionDisabled"] = "禁用",

                // Presets
                ["PresetSelectorHeader"] = "预设拦截方案 (Blocking Presets)",
                ["Preset_Basic"] = "基础",
                ["Preset_Basic_Sub"] = "~140K 规则",
                ["Preset_Basic_Desc"] = "极致高速优化 (~140,000 条规则)。基础广告拦截，适合轻量配置。",
                ["Preset_Standard"] = "标准 (推荐)",
                ["Preset_Standard_Sub"] = "~220K 规则",
                ["Preset_Standard_Desc"] = "性能与拦截效果的完美平衡 (~220,000 条规则)。推荐日常使用。",
                ["Preset_Advanced"] = "高级",
                ["Preset_Advanced_Sub"] = "~450K 规则",
                ["Preset_Advanced_Desc"] = "全面拦截广告、恶意网址、Cookie 提示与弹窗 (~450,000 条规则)。",
                ["Preset_Max"] = "最大防护",
                ["Preset_Max_Sub"] = "~650K+ 规则",
                ["Preset_Max_Desc"] = "终极全方位防护，深度反追踪与去烦扰 (~650,000+ 条规则)。",
                ["Preset_Custom"] = "自定义",
                ["Preset_Custom_Sub"] = "自定义选择",
                ["Preset_Custom_Desc"] = "根据您自定义勾选的规则列表。",
                ["PresetSwitchedLog"] = "已切换至拦截方案: '{0}' ({1} 个列表)",

                // 9 Categories
                ["Category_Builtin"] = "内置 / Built-in",
                ["Category_Builtin_Desc"] = "uBlock Origin 核心规则，用于防范恶意软件与修复网页。",
                ["Category_Core"] = "内置 / Built-in",
                ["Category_Core_Desc"] = "uBlock Origin 核心规则，用于防范恶意软件与修复网页。",
                ["Category_Ads"] = "广告拦截 / Ads",
                ["Category_Ads_Desc"] = "拦截网络广告、弹窗、视频广告和赞助横幅。",
                ["Category_Privacy"] = "隐私保护 / Privacy",
                ["Category_Privacy_Desc"] = "保护个人隐私，阻止行为跟踪器、统计分析与遥测。",
                ["Category_Security"] = "恶意软件与安全 / Malware & Security",
                ["Category_Security_Desc"] = "拦截恶意域名、钓鱼诈骗和勒索软件威胁。",
                ["Category_Multipurpose"] = "多用途 / Multipurpose",
                ["Category_Multipurpose_Desc"] = "综合广告、追踪服务器列表与 hosts 文件。",
                ["Category_Cookies"] = "Cookie 提示 / Cookie Notices",
                ["Category_Cookies_Desc"] = "自动隐藏并消除 GDPR Cookie 许可弹窗。",
                ["Category_Social"] = "社交组件 / Social Widgets",
                ["Category_Social_Desc"] = "拦截社交媒体分享按钮、点赞组件及跟踪插件。",
                ["Category_Annoyances"] = "烦人元素 / Annoyances",
                ["Category_Annoyances_Desc"] = "消除邮件订阅弹窗、调查问卷及推送通知。",
                ["Category_Regions"] = "地区与语言 / Regions & Languages",
                ["Category_Regions_Desc"] = "针对特定国家与语言网站优化的规则列表。",

                // Sub-Groups
                ["SubGroup_uBlockFilters"] = "uBlock filters",
                ["SubGroup_uBlockFilters_Desc"] = "uBlock Origin 核心规则",
                ["SubGroup_EasyListCookies"] = "EasyList/uBO – Cookie Notices",
                ["SubGroup_EasyListCookies_Desc"] = "来自 EasyList 和 uBO 的 Cookie 提示过滤",
                ["SubGroup_AdGuardCookies"] = "AdGuard/uBO – Cookie Notices",
                ["SubGroup_AdGuardCookies_Desc"] = "来自 AdGuard 和 uBO 的 Cookie 提示过滤",
                ["SubGroup_EasyListAnnoyances"] = "EasyList – Annoyances",
                ["SubGroup_EasyListAnnoyances_Desc"] = "EasyList 烦人元素过滤 (AI, Chat, Newsletters, Notifications)",
                ["SubGroup_AdGuardAnnoyances"] = "AdGuard – Annoyances",
                ["SubGroup_AdGuardAnnoyances_Desc"] = "AdGuard 烦人元素过滤 (Banners, Popups, Widgets)",
                ["SubGroup_Pl"] = "pl: Oficjalne Polskie Filtry",
                ["SubGroup_Pl_Desc"] = "uBlock Origin 波兰官方过滤规则",
                ["SubGroup_Ru"] = "ru, ua, uz, kz: RU AdList",
                ["SubGroup_Ru_Desc"] = "针对俄语及独联体区域网站的 RU AdList 过滤规则",

                // Filter Items (72 Items)
                ["Filter_ublock_filters_Name"] = "uBlock filters – Ads",
                ["Filter_ublock_filters_Desc"] = "uBlock Origin 核心基础过滤规则，用于广告去除与反绕过。",
                ["Filter_ublock_badware_Name"] = "uBlock filters – Badware risks",
                ["Filter_ublock_badware_Desc"] = "拦截高风险恶意软件、勒索及危险域名。",
                ["Filter_ublock_privacy_Name"] = "uBlock filters – Privacy",
                ["Filter_ublock_privacy_Desc"] = "进阶隐私保护，拦截高级行为跟踪器。",
                ["Filter_ublock_quick_fixes_Name"] = "uBlock filters – Quick fixes",
                ["Filter_ublock_quick_fixes_Desc"] = "针对故障网页及视频播放器的快速修复规则。",
                ["Filter_ublock_unbreak_Name"] = "uBlock filters – Unbreak",
                ["Filter_ublock_unbreak_Desc"] = "修复常见网站显示异常，防止页面布局损坏。",
                ["Filter_ublock_experimental_Name"] = "uBlock filters – Experimental",
                ["Filter_ublock_experimental_Desc"] = "uBlock Origin 最新实验性过滤规则。",

                ["Filter_easylist_Name"] = "EasyList",
                ["Filter_easylist_Desc"] = "全球最通用且最全面的基础广告拦截规则。",
                ["Filter_adguard_base_Name"] = "AdGuard – Ads",
                ["Filter_adguard_base_Desc"] = "来自 AdGuard 团队的标准综合广告拦截规则。",
                ["Filter_adguard_mobile_Name"] = "AdGuard – Mobile Ads",
                ["Filter_adguard_mobile_Desc"] = "针对移动端和 Web 应用优化的广告拦截规则。",
                ["Filter_youtube_adblock_Name"] = "YouTube Adblock & Scriptlets",
                ["Filter_youtube_adblock_Desc"] = "拦截 YouTube 视频前贴片、插播广告及赞助推荐横幅。",

                ["Filter_easyprivacy_Name"] = "EasyPrivacy",
                ["Filter_easyprivacy_Desc"] = "全面阻止行为跟踪器、统计分析代码及数据遥测。",
                ["Filter_adguard_tracking_Name"] = "AdGuard/uBO – URL Tracking Protection",
                ["Filter_adguard_tracking_Desc"] = "清除 URL 中的跟踪参数 (utm, fbclid, gclid)。",
                ["Filter_block_lan_Name"] = "Block Outsider Intrusion into LAN",
                ["Filter_block_lan_Desc"] = "阻止外部网站探测和访问局域网 (LAN) 资源。",

                ["Filter_malicious_urls_Name"] = "Online Malicious URL Blocklist",
                ["Filter_malicious_urls_Desc"] = "拦截钓鱼网站、恶意网址、欺诈及勒索传播源。",
                ["Filter_phishing_urls_Name"] = "Phishing URL Blocklist",
                ["Filter_phishing_urls_Desc"] = "拦截网络钓鱼链接及假冒银行网站。",

                ["Filter_peter_lowe_Name"] = "Peter Lowe’s Ad and tracking server list",
                ["Filter_peter_lowe_Desc"] = "Peter Lowe 维护的广告与跟踪服务器列表。",
                ["Filter_dan_pollock_Name"] = "Dan Pollock’s hosts file",
                ["Filter_dan_pollock_Desc"] = "Dan Pollock 著名的广告与垃圾域名 hosts 文件。",

                ["Filter_easylist_cookies_Name"] = "EasyList – Cookie Notices",
                ["Filter_easylist_cookies_Desc"] = "自动隐藏并拦截烦人的 GDPR Cookie 授权提示框。",
                ["Filter_ublock_cookies_easylist_Name"] = "uBlock filters – Cookie Notices",
                ["Filter_ublock_cookies_easylist_Desc"] = "uBlock Origin 补充的 Cookie 提示过滤规则。",
                ["Filter_adguard_cookies_Name"] = "AdGuard – Cookie Notices",
                ["Filter_adguard_cookies_Desc"] = "来自 AdGuard 团队的 Cookie 提示过滤规则。",
                ["Filter_ublock_cookies_adguard_Name"] = "uBlock filters – Cookie Notices",
                ["Filter_ublock_cookies_adguard_Desc"] = "配合 AdGuard 使用的 uBO Cookie 提示过滤规则。",

                ["Filter_easylist_social_Name"] = "EasyList – Social Widgets",
                ["Filter_easylist_social_Desc"] = "拦截社交媒体分享按钮与跟踪小组件 (Fanboy)。",
                ["Filter_adguard_social_Name"] = "AdGuard – Social Widgets",
                ["Filter_adguard_social_Desc"] = "来自 AdGuard 团队的社交组件过滤规则。",
                ["Filter_fanboy_antifacebook_Name"] = "Fanboy – Anti-Facebook",
                ["Filter_fanboy_antifacebook_Desc"] = "完全拦截 Facebook 嵌入式组件、跟踪脚本及插件。",

                ["Filter_easylist_ai_Name"] = "EasyList – AI Widgets",
                ["Filter_easylist_ai_Desc"] = "拦截 AI 聊天机器人悬浮窗口与辅助客服弹窗。",
                ["Filter_easylist_chat_Name"] = "EasyList – Chat Widgets",
                ["Filter_easylist_chat_Desc"] = "拦截自动弹出的在线客服与即时聊天工具。",
                ["Filter_easylist_newsletters_Name"] = "EasyList – Newsletter Notices",
                ["Filter_easylist_newsletters_Desc"] = "隐藏请求订阅邮件新闻周刊的弹窗。",
                ["Filter_easylist_notifications_Name"] = "EasyList – Notifications",
                ["Filter_easylist_notifications_Desc"] = "拦截浏览器推送通知授权请求。",
                ["Filter_easylist_other_annoyances_Name"] = "EasyList – Other Annoyances",
                ["Filter_easylist_other_annoyances_Desc"] = "消除 EasyList 包含的其他各类烦人视觉元素。",
                ["Filter_adguard_mobile_app_banners_Name"] = "AdGuard – Mobile App Banners",
                ["Filter_adguard_mobile_app_banners_Desc"] = "隐藏提示安装移动端 App 的应用推广横幅。",
                ["Filter_adguard_other_annoyances_Name"] = "AdGuard – Other Annoyances",
                ["Filter_adguard_other_annoyances_Desc"] = "来自 AdGuard 的其他网页烦人元素过滤规则。",
                ["Filter_adguard_popup_overlays_Name"] = "AdGuard – Popup Overlays",
                ["Filter_adguard_popup_overlays_Desc"] = "拦截付费墙遮罩、全屏弹窗与阅读阻断层。",
                ["Filter_adguard_widgets_Name"] = "AdGuard – Widgets",
                ["Filter_adguard_widgets_Desc"] = "隐藏悬浮干扰组件与网页浮层元素。",
                ["Filter_ublock_annoyances_Name"] = "uBlock filters – Annoyances",
                ["Filter_ublock_annoyances_Desc"] = "uBlock Origin 综合烦人元素去除过滤规则。",

                ["Filter_reg_al_Name"] = "al, xk: Adblock List for Albania",
                ["Filter_reg_al_Desc"] = "适用于阿尔巴尼亚和科索沃网站的广告拦截规则。",
                ["Filter_reg_bg_Name"] = "bg: Bulgarian Adblock list",
                ["Filter_reg_bg_Desc"] = "适用于保加利亚语网站的广告拦截规则。",
                ["Filter_reg_cn_Name"] = "cn, tw: AdGuard Chinese (中文)",
                ["Filter_reg_cn_Desc"] = "针对中文网站的全面广告与元素净化过滤规则。",
                ["Filter_reg_cz_Name"] = "cz, sk: EasyList Czech and Slovak",
                ["Filter_reg_cz_Desc"] = "适用于捷克和斯洛伐克网站的广告拦截规则。",
                ["Filter_reg_de_Name"] = "de, ch, at: EasyList Germany",
                ["Filter_reg_de_Desc"] = "适用于德语网站的附加广告拦截规则。",
                ["Filter_reg_ee_Name"] = "ee: Eesti saitidele kohandatud filter",
                ["Filter_reg_ee_Desc"] = "适用于爱沙尼亚语网站的广告拦截规则。",
                ["Filter_reg_eg_Name"] = "eg, sa, ma, dz: Liste AR",
                ["Filter_reg_eg_Desc"] = "适用于阿拉伯语网站的广告拦截规则。",
                ["Filter_reg_es_pt_Name"] = "es, ar, br, pt: AdGuard Spanish/Portuguese",
                ["Filter_reg_es_pt_Desc"] = "适用于西班牙语和葡萄牙语网站的广告过滤规则。",
                ["Filter_reg_es_Name"] = "es, ar, mx, co: EasyList Spanish",
                ["Filter_reg_es_Desc"] = "EasyList 西班牙语广告拦截规则。",
                ["Filter_reg_fi_Name"] = "fi: Adblock List for Finland",
                ["Filter_reg_fi_Desc"] = "适用于芬兰语网站的广告拦截规则。",
                ["Filter_reg_fr_Name"] = "fr, be, ca: AdGuard Français",
                ["Filter_reg_fr_Desc"] = "专为法语网站定制的广告拦截规则。",
                ["Filter_reg_gr_Name"] = "gr, cy: Greek AdBlock Filter",
                ["Filter_reg_gr_Desc"] = "适用于希腊语网站的广告拦截规则。",
                ["Filter_reg_hr_Name"] = "hr, rs: Dandelion Sprout's Serbo-Croatian filters",
                ["Filter_reg_hr_Desc"] = "适用于塞尔维亚、克罗地亚及波黑网站的过滤规则。",
                ["Filter_reg_hu_Name"] = "hu: hufilter",
                ["Filter_reg_hu_Desc"] = "适用于匈牙利语网站的广告拦截规则。",
                ["Filter_reg_id_Name"] = "id, my: ABPindo",
                ["Filter_reg_id_Desc"] = "适用于印度尼西亚和马来西亚网站的广告拦截规则。",
                ["Filter_reg_il_Name"] = "il: EasyList Hebrew",
                ["Filter_reg_il_Desc"] = "适用于希伯来语网站的广告拦截规则。",
                ["Filter_reg_in_Name"] = "in, lk, np: IndianList",
                ["Filter_reg_in_Desc"] = "适用于印度、斯里兰卡和尼泊尔网站的广告拦截规则。",
                ["Filter_reg_ir_Name"] = "ir: PersianBlocker",
                ["Filter_reg_ir_Desc"] = "适用于波斯语 (伊朗) 网站的广告拦截规则。",
                ["Filter_reg_is_Name"] = "is: Icelandic ABP List",
                ["Filter_reg_is_Desc"] = "适用于冰岛语网站的广告拦截规则。",
                ["Filter_reg_it_Name"] = "it: EasyList Italy",
                ["Filter_reg_it_Desc"] = "适用于意大利语网站的广告拦截规则。",
                ["Filter_reg_jp_Name"] = "jp: AdGuard Japanese",
                ["Filter_reg_jp_Desc"] = "拦截日语网站的广告、推广模块与冗余元素。",
                ["Filter_reg_kr_Name"] = "kr: 한국어 (Korean)",
                ["Filter_reg_kr_Desc"] = "针对韩语网站定制的高效广告拦截规则。",
                ["Filter_reg_lt_Name"] = "lt: EasyList Lithuania",
                ["Filter_reg_lt_Desc"] = "适用于立陶宛语网站的广告拦截规则。",
                ["Filter_reg_lv_Name"] = "lv: Latvian List",
                ["Filter_reg_lv_Desc"] = "适用于拉脱维亚语网站的广告拦截规则。",
                ["Filter_reg_mk_Name"] = "mk: Macedonian adBlock Filters",
                ["Filter_reg_mk_Desc"] = "适用于马其顿语网站的广告拦截规则。",
                ["Filter_reg_nl_Name"] = "nl, be: AdGuard Dutch",
                ["Filter_reg_nl_Desc"] = "适用于荷兰和比利时网站的广告拦截规则。",
                ["Filter_reg_no_Name"] = "no, dk, is: Dandelion Sprouts nordiske filtre",
                ["Filter_reg_no_Desc"] = "适用于北欧国家 (挪威、丹麦、冰岛) 的过滤规则。",
                ["Filter_reg_pl_cert_Name"] = "pl: CERT.PL's Warning List",
                ["Filter_reg_pl_cert_Desc"] = "波兰 CERT 恶意域名警告列表。",
                ["Filter_reg_pl_polskie_Name"] = "pl: Oficjalne Polskie Filtry do uBlocka Origin",
                ["Filter_reg_pl_polskie_Desc"] = "uBlock Origin 波兰官方过滤规则。",
                ["Filter_reg_ro_Name"] = "ro, md: Romanian Ad (ROad) Block List Light",
                ["Filter_reg_ro_Desc"] = "适用于罗马尼亚和摩尔多瓦网站的广告拦截规则。",
                ["Filter_reg_ru_adlist_Name"] = "ru, ua, uz, kz: RU AdList",
                ["Filter_reg_ru_adlist_Desc"] = "适用于俄语及独联体区域网站的综合广告过滤规则。",
                ["Filter_reg_ru_counters_Name"] = "ru, ua, uz, kz: RU AdList: Counters",
                ["Filter_reg_ru_counters_Desc"] = "拦截俄语区域的网站计数器和分析代码。",
                ["Filter_reg_se_Name"] = "se: Frellwit's Swedish Filter",
                ["Filter_reg_se_Desc"] = "适用于瑞典语网站的广告拦截规则。",
                ["Filter_reg_si_Name"] = "si: Slovenian List",
                ["Filter_reg_si_Desc"] = "适用于斯洛文尼亚语网站的广告拦截规则。",
                ["Filter_reg_th_Name"] = "th: EasyList Thailand",
                ["Filter_reg_th_Desc"] = "适用于泰语网站的广告拦截规则。",
                ["Filter_reg_tr_Name"] = "tr: AdGuard Turkish",
                ["Filter_reg_tr_Desc"] = "适用于土耳其语网站的广告拦截规则。",
                ["Filter_reg_ua_Name"] = "ua: AdGuard Ukrainian",
                ["Filter_reg_ua_Desc"] = "适用于乌克兰语网站的广告拦截规则。",
                ["Filter_reg_vn_Name"] = "vn: ABPVN List",
                ["Filter_reg_vn_Desc"] = "专为越南地区及越语新闻媒体网站定制的过滤规则。",
                ["Filter_reg_pl_Name"] = "pl: Oficjalne Polskie Filtry",
                ["Filter_reg_pl_Desc"] = "专为波兰地区及波兰语网站定制的官方过滤规则。",
                ["ProfileModeLabel"] = "Chrome 配置文件",
                ["ProfileMode_Managed"] = "专用配置文件（推荐）",
                ["ProfileMode_ManagedNote"] = "使用专用配置文件 %LOCALAPPDATA%\\ChromeNativeAdblock\\Profile。所有功能可用，包括外观过滤（CDP）与实时控制台。",
                ["ProfileMode_Real"] = "我的原始 Chrome 配置文件（保留登录）",
                ["ProfileMode_RealNote"] = "Chrome 136+ 禁止在原始配置文件上远程调试：外观过滤与实时控制台不可用；网络广告拦截与 MV2 仍正常。MV2 修复会修改该配置文件。",
                ["ProfileMode_RealMissingNote"] = "未找到原始配置文件： ",
            }
        };

    public static string CurrentLanguage { get; private set; } = Vietnamese;

    public static void Initialize()
    {
        var defaultLang = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant() switch
        {
            "vi" => Vietnamese,
            "zh" => Chinese,
            _ => English
        };

        var saved = TryReadSavedLanguage();
        CurrentLanguage = NormalizeLanguage(saved ?? defaultLang);
    }

    public static void SetLanguage(string language)
    {
        var normalized = NormalizeLanguage(language);
        if (string.Equals(CurrentLanguage, normalized, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        CurrentLanguage = normalized;
        try
        {
            var dir = Path.GetDirectoryName(SettingsPath);
            if (!string.IsNullOrWhiteSpace(dir))
            {
                Directory.CreateDirectory(dir);
            }
            File.WriteAllText(SettingsPath, CurrentLanguage);
        }
        catch { }

        LanguageChanged?.Invoke();
    }

    public static string Text(string key, params object[] arguments)
    {
        if (Translations.TryGetValue(CurrentLanguage, out var langDict) &&
            langDict.TryGetValue(key, out var text))
        {
            return arguments.Length == 0 ? text : string.Format(CultureInfo.InvariantCulture, text, arguments);
        }

        if (Translations[English].TryGetValue(key, out var enText))
        {
            return arguments.Length == 0 ? enText : string.Format(CultureInfo.InvariantCulture, enText, arguments);
        }

        return key;
    }

    private static string? TryReadSavedLanguage()
    {
        try
        {
            if (File.Exists(SettingsPath))
            {
                var content = File.ReadAllText(SettingsPath).Trim();
                if (!string.IsNullOrWhiteSpace(content))
                {
                    return content;
                }
            }
        }
        catch { }

        return null;
    }

    private static string NormalizeLanguage(string language)
    {
        if (string.Equals(language, Vietnamese, StringComparison.OrdinalIgnoreCase)) return Vietnamese;
        if (string.Equals(language, Chinese, StringComparison.OrdinalIgnoreCase)) return Chinese;
        return English;
    }
}
